[package]
name = "ygen-mc"
version = "0.1.0"
edition = "2021"
description = "Ygens machine code playground"
license = "Apache-2.0"

[[bin]]
name = "ygen-mc"
path = "main.rs"

[dependencies]
Ygen = "0.1.2"